# Generated by Django 4.2.30 on 2026-07-08 18:51

import core.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Categoría (Ej: Serie A, Femenino)')),
                ('color_carnet', models.CharField(default='#1D4ED8', help_text='Color en HEX para los carnets (Ej: #FF0000 para rojo, #00FF00 para verde)', max_length=7)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('precio_hora_cancha', models.DecimalField(decimal_places=2, default=15.0, max_digits=6)),
                ('logo_sistema', models.ImageField(blank=True, null=True, upload_to='configuracion/', verbose_name='Logo del Sistema')),
            ],
        ),
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: GOLAZO2026', max_length=20, unique=True)),
                ('descuento', models.DecimalField(decimal_places=2, help_text='Monto en $ a descontar', max_digits=5)),
                ('tipo', models.CharField(choices=[('CANCHA', 'Alquiler de Cancha'), ('TORNEO', 'Inscripción de Campeonato')], max_length=15)),
                ('activo', models.BooleanField(default=True)),
                ('usos_actuales', models.PositiveIntegerField(default=0)),
                ('limite_usos', models.PositiveIntegerField(blank=True, help_text='Dejar vacío para ilimitado', null=True)),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('escudo', models.ImageField(blank=True, null=True, upload_to='escudos/')),
                ('telefono_contacto', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular de Contacto')),
                ('nombre_suplente_1', models.CharField(blank=True, max_length=100)),
                ('nombre_suplente_2', models.CharField(blank=True, max_length=100)),
                ('pagado', models.BooleanField(default=False, verbose_name='Inscripción Pagada')),
                ('monto_reembolso', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cupos_pagados', models.PositiveIntegerField(default=0, verbose_name='Nº de Jugadores Pagados/Habilitados')),
                ('puntos_bonificacion', models.IntegerField(default=0)),
                ('grupo_fase2', models.CharField(blank=True, max_length=1, null=True)),
                ('estado_inscripcion', models.CharField(choices=[('PENDIENTE', '⏳ Pendiente de Aprobación'), ('APROBADO', '✅ Aprobado'), ('RECHAZADO', '❌ Rechazado')], default='PENDIENTE', max_length=10)),
                ('sancionado_hasta', models.DateField(blank=True, null=True, verbose_name='Equipo en Lista Negra hasta:')),
                ('dirigente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_dirigido', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FotoGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria/', verbose_name='Foto de la Cancha')),
                ('titulo', models.CharField(blank=True, max_length=50, verbose_name='Título corto (Opcional)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
                ('activa', models.BooleanField(default=True, verbose_name='Mostrar en el inicio')),
            ],
            options={
                'verbose_name': 'Foto de Galería',
                'verbose_name_plural': 'Galería de la Cancha',
                'ordering': ['orden', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HorarioCancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Costo del Turno')),
                ('activo', models.BooleanField(default=True, verbose_name='Disponible para alquilar')),
            ],
            options={
                'ordering': ['hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras y espacios. No se permiten números ni símbolos.', regex='^[a-zA-ZñÑáéíóúÁÉÍÓÚ\\s]+$')])),
                ('dorsal', models.PositiveIntegerField()),
                ('cedula', models.CharField(max_length=15, validators=[core.models.validar_cedula_db])),
                ('foto', models.ImageField(blank=True, null=True, upload_to='jugadores/')),
                ('rojas_directas_acumuladas', models.PositiveIntegerField(default=0)),
                ('expulsado_torneo', models.BooleanField(default=False)),
                ('partidos_suspension', models.IntegerField(default=0, verbose_name='Partidos de Suspensión')),
                ('sancionado_hasta', models.DateField(blank=True, null=True, verbose_name='Jugador Suspendido hasta:')),
                ('bloqueado_por_cuota', models.BooleanField(default=False, verbose_name='Bloqueado por cuota de partidos')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='core.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informe_vocal', models.TextField(blank=True, null=True)),
                ('informe_arbitro', models.TextField(blank=True, null=True)),
                ('validado_local', models.BooleanField(default=False)),
                ('validado_visita', models.BooleanField(default=False)),
                ('numero_fecha', models.PositiveIntegerField(default=1)),
                ('etapa', models.CharField(choices=[('F1', 'Fase 1'), ('F2', 'Fase 2'), ('4TOS', 'Cuartos de Final'), ('SEMI', 'Semifinal'), ('TERC', 'Tercer Lugar'), ('FINAL', 'Final')], default='F1', max_length=5)),
                ('cancha', models.CharField(default='Cancha Principal', max_length=100)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('goles_local', models.PositiveIntegerField(default=0)),
                ('goles_visita', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('PROG', 'Programado'), ('VIVO', 'En Vivo (Arbitrando)'), ('ACTA', 'En Acta (Faltan Firmas)'), ('JUG', 'Finalizado'), ('WO', 'Walkover')], default='PROG', max_length=4)),
                ('sanciones_aplicadas', models.BooleanField(default=False, verbose_name='¿Sanciones ya procesadas?')),
                ('hubo_penales', models.BooleanField(default=False, verbose_name='¿Hubo Penales?')),
                ('penales_local', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('penales_visita', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='core.equipo')),
                ('equipo_visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visita', to='core.equipo')),
                ('ganador_wo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='publicidad/', verbose_name='Banner Publicitario')),
                ('empresa', models.CharField(max_length=100, verbose_name='Nombre de la Empresa o Negocio')),
                ('enlace', models.URLField(blank=True, null=True, verbose_name='Link de WhatsApp o Red Social (Opcional)')),
                ('activa', models.BooleanField(default=True, verbose_name='Mostrar anuncio')),
            ],
            options={
                'verbose_name': 'Publicidad',
                'verbose_name_plural': 'Publicidades',
            },
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
                ('cobro_por_jugador', models.BooleanField(default=False, verbose_name='¿Cobrar inscripción POR JUGADOR en vez de equipo?')),
                ('costo_inscripcion', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo x Equipo')),
                ('costo_inscripcion_jugador', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo x Jugador')),
                ('costo_amarilla', models.DecimalField(decimal_places=2, default=0.5, max_digits=5, verbose_name='Multa Amarilla ($)')),
                ('costo_roja', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Multa Roja ($)')),
                ('inscripcion_abierta', models.BooleanField(default=True, verbose_name='¿Inscripción Habilitada?')),
                ('fecha_limite_inscripcion', models.DateField(blank=True, null=True)),
                ('fase1_ida_vuelta', models.BooleanField(default=False, verbose_name='Fase 1 (Todos contra Todos) - Ida o Vuelta')),
                ('fase2_ida_vuelta', models.BooleanField(default=False, verbose_name='Fase 2 (Grupos) - Ida y Vuelta Acumulativa')),
                ('fase3_ida_vuelta', models.BooleanField(default=False, verbose_name='Fase 3 (Eliminatorias/Cuartos) - Ida y Vuelta')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria', verbose_name='Categoría')),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INSCRIPCION', 'Deuda por Inscripción'), ('AMARILLA', 'Tarjeta Amarilla'), ('ROJA', 'Tarjeta Roja'), ('ADMIN', 'Sanción Administrativa')], max_length=15)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('pagada', models.BooleanField(default=False, verbose_name='¿Pagada?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanciones', to='core.equipo')),
                ('jugador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.jugador')),
                ('partido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.partido')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.torneo')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaCancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('precio_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('pagado', models.BooleanField(default=False)),
                ('es_torneo', models.BooleanField(default=False, verbose_name='Bloqueo por Torneo')),
                ('motivo_bloqueo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', '⏳ Pendiente'), ('ACTIVA', '✅ Confirmada'), ('CANCELADA', '🚫 Cancelada')], default='PENDIENTE', max_length=15)),
                ('cupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cupon')),
                ('partido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserva_bloqueo', to='core.partido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ORG', 'Organizador'), ('VOC', 'Vocal de Mesa'), ('DIR', 'Dirigente de Equipo'), ('FAN', 'Aficionado / Cliente')], default='FAN', max_length=3)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('sancionado_hasta', models.DateField(blank=True, null=True, verbose_name='Suspendido (Lista Negra) hasta:')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='partido',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.torneo'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='pagos/')),
                ('validado', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True, max_length=500, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.equipo')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='core.torneo'),
        ),
        migrations.CreateModel(
            name='DetallePartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GOL', '⚽ Gol'), ('ASIS', '✅ Asistencia'), ('TA', '🟨 Amarilla'), ('TR', '🟥 Roja'), ('DA', '🟨🟨 Doble A.'), ('AZUL', '👕 Uniforme'), ('EBRI', '🍺 Ebrio'), ('STAR', '⭐ Figura')], max_length=5)),
                ('minuto', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('equipo_incidencia', models.ForeignKey(blank=True, help_text='Asegura que los goles no se fuguen si se traspasa al jugador', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.partido')),
            ],
        ),
        migrations.CreateModel(
            name='AbonoSancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('partido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonos_cobrados', to='core.partido')),
                ('sancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_abonos', to='core.sancion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='jugador',
            constraint=models.UniqueConstraint(fields=('equipo', 'dorsal'), name='unico_dorsal_por_equipo'),
        ),
    ]
