# Generated by Django 6.0.1 on 2026-03-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_reservacancha_monto_reembolso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='puede_fichar',
            field=models.BooleanField(default=False, verbose_name='¿Permiso para Fichar?'),
        ),
    ]
