# Generated by Django 6.0.1 on 2026-03-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_equipo_puede_fichar'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='partidos_suspension',
            field=models.IntegerField(default=0, verbose_name='Partidos de Suspensión'),
        ),
    ]
