# Generated by Django 5.2.12 on 2026-03-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_jugador_partidos_suspension"),
    ]

    operations = [
        migrations.AlterField(
            model_name="torneo",
            name="costo_amarilla",
            field=models.DecimalField(
                decimal_places=2,
                default=0.5,
                max_digits=5,
                verbose_name="Multa Amarilla ($)",
            ),
        ),
    ]
