# Generated by Django 6.0.1 on 2026-03-09 15:36

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_jugador_partidos_suspension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multa',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='multa',
            name='partido',
        ),
        migrations.AlterField(
            model_name='jugador',
            name='cedula',
            field=models.CharField(max_length=15, unique=True, validators=[core.models.validar_cedula_db]),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nombres',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras y espacios. No se permiten números ni símbolos.', regex='^[a-zA-ZñÑáéíóúÁÉÍÓÚ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='partido',
            name='fecha_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='pagada',
            field=models.BooleanField(default=False, verbose_name='¿Pagada?'),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='tipo',
            field=models.CharField(choices=[('INSCRIPCION', 'Deuda por Inscripción'), ('AMARILLA', 'Tarjeta Amarilla'), ('ROJA', 'Tarjeta Roja'), ('ADMIN', 'Sanción Administrativa')], max_length=15),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='costo_amarilla',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5, verbose_name='Multa Amarilla ($)'),
        ),
        migrations.AddConstraint(
            model_name='jugador',
            constraint=models.UniqueConstraint(fields=('equipo', 'dorsal'), name='unico_dorsal_por_equipo'),
        ),
        migrations.DeleteModel(
            name='Multa',
        ),
    ]
