# Generated by Django 6.0.1 on 2026-03-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_multa_equipo_remove_multa_partido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioCancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Costo por Hora')),
                ('activo', models.BooleanField(default=True, verbose_name='Disponible para alquilar')),
            ],
            options={
                'verbose_name': 'Horario de Cancha',
                'verbose_name_plural': 'Horarios de Cancha',
                'ordering': ['hora_inicio'],
            },
        ),
    ]
