# Generated by Django 6.0.1 on 2026-03-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_horariocancha'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria/', verbose_name='Foto de la Cancha')),
                ('titulo', models.CharField(blank=True, max_length=50, verbose_name='Título corto (Opcional)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
                ('activa', models.BooleanField(default=True, verbose_name='Mostrar en el inicio')),
            ],
            options={
                'verbose_name': 'Foto de Galería',
                'verbose_name_plural': 'Galería de la Cancha',
                'ordering': ['orden', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='publicidad/', verbose_name='Banner Publicitario')),
                ('empresa', models.CharField(max_length=100, verbose_name='Nombre de la Empresa o Negocio')),
                ('enlace', models.URLField(blank=True, null=True, verbose_name='Link de WhatsApp o Red Social (Opcional)')),
                ('activa', models.BooleanField(default=True, verbose_name='Mostrar anuncio')),
            ],
            options={
                'verbose_name': 'Publicidad',
                'verbose_name_plural': 'Publicidades',
            },
        ),
    ]
