# Generated by Django 5.2.12 on 2026-03-10 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_torneo_costo_amarilla"),
        ("core", "0021_fotogaleria_publicidad"),
    ]

    operations = []
