# Generated by Django 6.0.1 on 2026-03-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_merge_20260310_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='sancion',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
