# Generated by Django 6.0.1 on 2026-03-10 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_sancion_monto_pagado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonoSancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('sancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_abonos', to='core.sancion')),
            ],
        ),
    ]
