# Generated by Django 6.0.1 on 2026-03-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_abonosancion'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular de Contacto'),
        ),
    ]
