# Generated by Django 6.0.1 on 2026-03-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_equipo_telefono_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='estado',
            field=models.CharField(choices=[('PROG', 'Programado'), ('VIVO', 'En Vivo (Arbitrando)'), ('ACTA', 'En Acta (Faltan Firmas)'), ('JUG', 'Finalizado'), ('WO', 'Walkover')], default='PROG', max_length=4),
        ),
    ]
