# Generated by Django 6.0.1 on 2026-03-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_partido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='hubo_penales',
            field=models.BooleanField(default=False, verbose_name='¿Se definió por penales?'),
        ),
        migrations.AddField(
            model_name='partido',
            name='penales_local',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='penales_visita',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='torneo',
            name='fase2_ida_vuelta',
            field=models.BooleanField(default=False, verbose_name='Fase 2 (Grupos) - Ida y Vuelta'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='fase3_ida_vuelta',
            field=models.BooleanField(default=False, verbose_name='Fase 3 (Cuartos) - Ida y Vuelta'),
        ),
    ]
