# Generated by Django 6.0.1 on 2026-03-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_partido_hubo_penales_partido_penales_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='etapa',
            field=models.CharField(choices=[('F1', 'Fase 1'), ('F2', 'Fase 2'), ('4TOS', 'Cuartos'), ('SEMI', 'Semifinal'), ('TERC', 'Tercer Lugar'), ('FINAL', 'Final')], default='F1', max_length=5),
        ),
        migrations.AlterField(
            model_name='partido',
            name='hubo_penales',
            field=models.BooleanField(default=False, verbose_name='¿Hubo Penales?'),
        ),
    ]
