# Generated by Django 6.0.1 on 2026-04-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_partido_etapa_alter_partido_hubo_penales'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='es_refuerzo',
            field=models.BooleanField(default=False, verbose_name='¿Es Refuerzo?'),
        ),
    ]
