# Generated by Django 6.0.1 on 2026-05-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_jugador_es_refuerzo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='vuelta',
            field=models.IntegerField(default=1, verbose_name='Vuelta (1 o 2)'),
        ),
    ]
